# Generated by Django 5.2.17 on 2026-09-09 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectorFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers sort first in lists.')),
            ],
            options={
                'verbose_name': 'connector family',
                'verbose_name_plural': 'connector families',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ConnectorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Specific connector within the family, e.g. "XLR3" or "TRS".', max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('abbreviation', models.CharField(blank=True, help_text='Common shorthand, e.g. "TT" or "TRS".', max_length=20)),
                ('contact_count', models.PositiveSmallIntegerField(blank=True, help_text='Number of pins / poles / conductors (3 for XLR3, 2 for TS).', null=True)),
                ('description', models.TextField(blank=True)),
                ('typical_uses', models.TextField(blank=True, help_text='Common signals or gear this connector is used for.')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to retire a connector without deleting historical data.')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers sort first within the family.')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='types', to='catalog.connectorfamily')),
            ],
            options={
                'ordering': ['family__sort_order', 'family__name', 'sort_order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('family', 'name'), name='unique_connectortype_name_per_family'), models.UniqueConstraint(fields=('family', 'slug'), name='unique_connectortype_slug_per_family')],
            },
        ),
    ]
